### **Data Processsing**

In [10]:
# Loading the data sets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# import seaborn as sns

### **EDA**

In [ ]:
train_df.head()

,sample_id,catalog_content,image_link,price
0,33127,"Item Name: La Victoria Green Taco Sauce Mild, ...",https://m.media-amazon.com/images/I/51mo8htwTH...,4.89
1,198967,"Item Name: Salerno Cookies, The Original Butte...",https://m.media-amazon.com/images/I/71YtriIHAA...,13.12
2,261251,"Item Name: Bear Creek Hearty Soup Bowl, Creamy...",https://m.media-amazon.com/images/I/51+PFEe-w-...,1.97
3,55858,Item Name: Judee’s Blue Cheese Powder 11.25 oz...,https://m.media-amazon.com/images/I/41mu0HAToD...,30.34
4,292686,"Item Name: kedem Sherry Cooking Wine, 12.7 Oun...",https://m.media-amazon.com/images/I/41sA037+Qv...,66.49

In [5]:
# Loading the .env file
from dotenv import load_dotenv
import os
load_dotenv()
# Accessing the environment variable from the .env file 
api_key = os.getenv('DAGSHUB_USERNAME')
print(f'DAGSHUB_USERNAME Key: {api_key}')

DAGSHUB_USERNAME Key: arpitkumar2004

In [13]:
# Pull the data from DagsHub 
from dagshub.streaming import DagsHubFilesystem
fs = DagsHubFilesystem(".", repo_url="https://dagshub.com/arpitkumar2004/A_ML_25")
f = fs.open("data/raw/train.csv")

Accessing as arpitkumar2004

In [15]:
train_df = pd.read_csv(r'C:\Users\RDRL\Desktop\A_ML_25\notebooks\data\raw\train.csv')
train_df.head()

,sample_id,catalog_content,image_link,price
0,33127,"Item Name: La Victoria Green Taco Sauce Mild, ...",https://m.media-amazon.com/images/I/51mo8htwTH...,4.89
1,198967,"Item Name: Salerno Cookies, The Original Butte...",https://m.media-amazon.com/images/I/71YtriIHAA...,13.12
2,261251,"Item Name: Bear Creek Hearty Soup Bowl, Creamy...",https://m.media-amazon.com/images/I/51+PFEe-w-...,1.97
3,55858,Item Name: Judee’s Blue Cheese Powder 11.25 oz...,https://m.media-amazon.com/images/I/41mu0HAToD...,30.34
4,292686,"Item Name: kedem Sherry Cooking Wine, 12.7 Oun...",https://m.media-amazon.com/images/I/41sA037+Qv...,66.49

In [16]:
train_df.columns

Index(['sample_id', 'catalog_content', 'image_link', 'price'], dtype='object')